/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginLibreria;

import Includes.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Gonzalo CH
 */
public class PanelFacturacion extends javax.swing.JPanel {

    /**
     * Creates new form PanelFacturacion
     */
    public PanelFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdFact = new javax.swing.JLabel();
        txtIdFact = new javax.swing.JTextField();
        btnBuscarFact = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblIdDoc = new javax.swing.JLabel();
        lblClienteDoc = new javax.swing.JLabel();
        lblFechaDoc = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblDetallesDoc = new javax.swing.JLabel();
        lblLibroDoc = new javax.swing.JLabel();
        lblPrecioDoc = new javax.swing.JLabel();
        lblCantidadDoc = new javax.swing.JLabel();
        lblSubDoc = new javax.swing.JLabel();

        lblIdFact.setText("ID FACTURA:");

        btnBuscarFact.setText("Buscar");
        btnBuscarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFactActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblIdDoc.setText("ID FACTURA:");

        lblClienteDoc.setText("CLIENTE:");

        lblFechaDoc.setText("FECHA:");

        lblLinea.setText("--------------------------------------------------------------------------------------------------------------------------");

        lblDetallesDoc.setText("DETALLES:");

        lblLibroDoc.setText("LIBRO");

        lblPrecioDoc.setText("PRECIO");

        lblCantidadDoc.setText("CANTIDAD");

        lblSubDoc.setText("SUBTOTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdDoc)
                                    .addComponent(lblClienteDoc)
                                    .addComponent(lblFechaDoc)
                                    .addComponent(lblDetallesDoc))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLibroDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrecioDoc)
                        .addGap(38, 38, 38)
                        .addComponent(lblCantidadDoc)
                        .addGap(39, 39, 39)
                        .addComponent(lblSubDoc)
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClienteDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaDoc)
                .addGap(18, 18, 18)
                .addComponent(lblLinea)
                .addGap(18, 18, 18)
                .addComponent(lblDetallesDoc)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibroDoc)
                    .addComponent(lblPrecioDoc)
                    .addComponent(lblCantidadDoc)
                    .addComponent(lblSubDoc))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdFact)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdFact, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarFact, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdFact)
                    .addComponent(txtIdFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFactActionPerformed
        Conexion conn = new Conexion();
        conn.estableceConexion("Eduardo","987456321");
        String sql = """
                  SELECT COUNT(*) FROM libreria.libro;
                  """;
        try {
            PreparedStatement st = conn.cn.prepareStatement(sql) ;
            ResultSet rs = st.executeQuery();
            while (rs.next()) {                
                System.out.println("Numero de libros: " + rs.getString("count"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarFactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFact;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadDoc;
    private javax.swing.JLabel lblClienteDoc;
    private javax.swing.JLabel lblDetallesDoc;
    private javax.swing.JLabel lblFechaDoc;
    private javax.swing.JLabel lblIdDoc;
    private javax.swing.JLabel lblIdFact;
    private javax.swing.JLabel lblLibroDoc;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblPrecioDoc;
    private javax.swing.JLabel lblSubDoc;
    private javax.swing.JTextField txtIdFact;
    // End of variables declaration//GEN-END:variables
}
